apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: aar5249/delivery-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: JWT_SECRET
          value: "smartdispatch_secret_key"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP
